// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "menu_dropdown_test.h"

Fl_Group *group_register=(Fl_Group *)0;

Fl_Menu_Button *menubtn_books=(Fl_Menu_Button *)0;

static void cb_Edit(Fl_Menu_*, void*) {
  MENU_BTN_CB();
}

static void cb_Remove(Fl_Menu_*, void*) {
  MENU_BTN_CB();
}

static void cb_Search(Fl_Menu_*, void*) {
  MENU_BTN_CB();
}

Fl_Menu_Item menu_menubtn_books[] = {
 {"Add Book", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(add_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Books", 0,  (Fl_Callback*)cb_Edit, (void*)(edit_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Books", 0,  (Fl_Callback*)cb_Remove, (void*)(remove_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Search Books", 0,  (Fl_Callback*)cb_Search, (void*)(search_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *menubtn_readers=(Fl_Menu_Button *)0;

static void cb_Add(Fl_Menu_*, void*) {
  MENU_BTN_CB();
}

static void cb_Remove1(Fl_Menu_*, void*) {
  MENU_BTN_CB();
}

static void cb_Search1(Fl_Menu_*, void*) {
  MENU_BTN_CB();
}

Fl_Menu_Item menu_menubtn_readers[] = {
 {"Add Readers", 0,  (Fl_Callback*)cb_Add, (void*)(add_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Readers", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Readers", 0,  (Fl_Callback*)cb_Remove1, (void*)(remove_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Search Readers", 0,  (Fl_Callback*)cb_Search1, (void*)(search_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *menubtn_loans=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_menubtn_loans[] = {
 {"Add Loans", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Loans", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Loans", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Expired Loans", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Search Loans", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *menubtn_databases=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_menubtn_databases[] = {
 {"Backup", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Offline", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Online", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Direct connection", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Local peer-to-peer (LAN)", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Online peer-to-peer (internet)", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *menubtn_settings=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_menubtn_settings[] = {
 {"Account", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Networking", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Other", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *menubtn_login=(Fl_Menu_Button *)0;

Fl_Menu_Button *menubtn_register=(Fl_Menu_Button *)0;

Fl_Group *group_login=(Fl_Group *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(554, 370, "Bookworm");
    w = o; if (w) {/* empty */}
    { group_register = new Fl_Group(0, 25, 550, 340);
      group_register->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(195, 25, 155, 0, "Register");
        o->labelsize(41);
        o->align(Fl_Align(34));
      } // Fl_Text_Display* o
      { Fl_Input* o = new Fl_Input(105, 75, 420, 30, "Username");
        o->labelsize(19);
      } // Fl_Input* o
      { Fl_Input* o = new Fl_Input(105, 115, 420, 30, "Password");
        o->labelsize(19);
      } // Fl_Input* o
      { new Fl_Input(110, 155, 415, 30, "Password again");
      } // Fl_Input* o
      { Fl_Input_Choice* o = new Fl_Input_Choice(225, 190, 155, 65, "Role");
        o->color((Fl_Color)34);
        o->selection_color((Fl_Color)34);
        o->labelsize(31);
        o->textsize(21);
      } // Fl_Input_Choice* o
      { Fl_Button* o = new Fl_Button(375, 290, 175, 75, "Register");
        o->color((Fl_Color)34);
        o->selection_color((Fl_Color)35);
        o->labelsize(31);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(190, 290, 180, 75, "Clear");
        o->color((Fl_Color)34);
        o->selection_color((Fl_Color)35);
        o->labelsize(31);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(5, 290, 180, 75, "Back");
        o->color((Fl_Color)35);
        o->selection_color((Fl_Color)35);
        o->labelsize(31);
      } // Fl_Button* o
      group_register->end();
      Fl_Group::current()->resizable(group_register);
    } // Fl_Group* group_register
    { menubtn_books = new Fl_Menu_Button(0, 0, 55, 25, "Books");
      menubtn_books->menu(menu_menubtn_books);
    } // Fl_Menu_Button* menubtn_books
    { menubtn_readers = new Fl_Menu_Button(55, 0, 80, 25, "Readers");
      menubtn_readers->menu(menu_menubtn_readers);
    } // Fl_Menu_Button* menubtn_readers
    { menubtn_loans = new Fl_Menu_Button(135, 0, 65, 25, "Loans");
      menubtn_loans->menu(menu_menubtn_loans);
    } // Fl_Menu_Button* menubtn_loans
    { menubtn_databases = new Fl_Menu_Button(200, 0, 90, 25, "Databases");
      menubtn_databases->menu(menu_menubtn_databases);
    } // Fl_Menu_Button* menubtn_databases
    { menubtn_settings = new Fl_Menu_Button(290, 0, 70, 25, "Settings");
      menubtn_settings->menu(menu_menubtn_settings);
    } // Fl_Menu_Button* menubtn_settings
    { menubtn_login = new Fl_Menu_Button(360, 0, 85, 25, "Log in/out");
    } // Fl_Menu_Button* menubtn_login
    { menubtn_register = new Fl_Menu_Button(445, 0, 85, 25, "Register");
    } // Fl_Menu_Button* menubtn_register
    { group_login = new Fl_Group(0, 25, 530, 325);
      group_login->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(200, 30, 155, 0, "Login");
        o->labelsize(41);
        o->align(Fl_Align(34));
      } // Fl_Text_Display* o
      { Fl_Input* o = new Fl_Input(110, 80, 420, 30, "Username");
        o->labelsize(19);
      } // Fl_Input* o
      { Fl_Input* o = new Fl_Input(110, 120, 420, 30, "Password");
        o->labelsize(19);
      } // Fl_Input* o
      { Fl_Button* o = new Fl_Button(360, 160, 170, 185, "Register");
        o->color((Fl_Color)34);
        o->selection_color((Fl_Color)35);
        o->labelsize(31);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(180, 160, 175, 185, "Clear");
        o->color((Fl_Color)34);
        o->selection_color((Fl_Color)35);
        o->labelsize(31);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(10, 160, 160, 185, "Back");
        o->color((Fl_Color)35);
        o->selection_color((Fl_Color)35);
        o->labelsize(31);
      } // Fl_Button* o
      group_login->end();
    } // Fl_Group* group_login
    o->end();
  } // Fl_Double_Window* o
  return w;
}
