// generated by Fast Light User Interface Designer (fluid) version 1.0311

#include "shelfsight_gui.h"

Fl_Double_Window *window_assistant=(Fl_Double_Window *)0;

Fl_Image *assistant_image=(Fl_Image *)0;

Fl_Menu_Button *mnubtn_books=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_books[] = {
 {"Add Books", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(add_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Books", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(edit_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Books", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(remove_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Manage Categories", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(manage_categories), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_readers=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_readers[] = {
 {"Add Readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(add_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(edit_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(remove_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Import readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(import_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_loans=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_loans[] = {
 {"Add Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(add_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(edit_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(remove_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Expired Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(expired_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_databases=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_databases[] = {
 {"Load Default DBs", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Backup", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Offline", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_offline), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Online", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Direct connection", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_directconnection), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Local peer-to-peer (LAN)", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_localp2p), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Online peer-to-peer (internet)", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_onlinep2p), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"Manage", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Add Database", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Database", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Select current DBs", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Select default (persistent)", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_settings=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_settings[] = {
 {"Account", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_account), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Theme", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_theme), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Performance", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_performance), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Networking", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_networking), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Other", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_other), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_login=(Fl_Menu_Button *)0;

Fl_Menu_Button *mnubtn_register=(Fl_Menu_Button *)0;

Fl_Menu_Button *menubtn_clear=(Fl_Menu_Button *)0;

Fl_Group *group_register=(Fl_Group *)0;

Fl_Group *group_login=(Fl_Group *)0;

Fl_Group *group_addbooks=(Fl_Group *)0;

Fl_Group *group_addreaders=(Fl_Group *)0;

Fl_Group *group_addloans=(Fl_Group *)0;

Fl_Group *group_editbooks=(Fl_Group *)0;

Fl_Group *group_deletebooks=(Fl_Group *)0;

Fl_Group *group_editreaders=(Fl_Group *)0;

Fl_Group *group_deletereaders=(Fl_Group *)0;

Fl_Group *group_editloans=(Fl_Group *)0;

Fl_Group *group_markloans=(Fl_Group *)0;

Fl_Double_Window* make_window() {
  { window_assistant = new Fl_Double_Window(421, 166, "Merlin the Mole - your assistant");
    { Fl_Text_Display* o = new Fl_Text_Display(0, 0, 10, 25, "Merlin the Mole");
      o->labelsize(21);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { // The image of the agent
      assistant_image = new Fl_Image(0, 25, 145, 135);
      assistant_image->box(FL_NO_BOX);
      assistant_image->color(FL_BACKGROUND_COLOR);
      assistant_image->selection_color(FL_BACKGROUND_COLOR);
      assistant_image->labeltype(FL_NORMAL_LABEL);
      assistant_image->labelfont(0);
      assistant_image->labelsize(14);
      assistant_image->labelcolor(FL_FOREGROUND_COLOR);
      assistant_image->align(Fl_Align(FL_ALIGN_CENTER));
      assistant_image->when(FL_WHEN_RELEASE);
    } // Fl_Image* assistant_image
    { Fl_Input* o = new Fl_Input(145, 140, 190, 25, "Your question:");
      o->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Input* o
    { Fl_Button* o = new Fl_Button(335, 140, 85, 25, "Submit");
      o->labelsize(16);
    } // Fl_Button* o
    { new Fl_Text_Display(160, 15, 255, 110, "Answer");
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(360, 0, 55, 15, "Close");
      o->color((Fl_Color)41);
    } // Fl_Button* o
    window_assistant->end();
  } // Fl_Double_Window* window_assistant
  { Fl_Double_Window* o = new Fl_Double_Window(542, 373, "ShelfSight");
    w = o; if (w) {/* empty */}
    { mnubtn_books = new Fl_Menu_Button(0, 0, 55, 25, "Books");
      mnubtn_books->menu(menu_mnubtn_books);
    } // Fl_Menu_Button* mnubtn_books
    { mnubtn_readers = new Fl_Menu_Button(55, 0, 70, 25, "Readers");
      mnubtn_readers->menu(menu_mnubtn_readers);
    } // Fl_Menu_Button* mnubtn_readers
    { mnubtn_loans = new Fl_Menu_Button(125, 0, 60, 25, "Loans");
      mnubtn_loans->menu(menu_mnubtn_loans);
    } // Fl_Menu_Button* mnubtn_loans
    { mnubtn_databases = new Fl_Menu_Button(185, 0, 85, 25, "Databases");
      mnubtn_databases->menu(menu_mnubtn_databases);
    } // Fl_Menu_Button* mnubtn_databases
    { mnubtn_settings = new Fl_Menu_Button(270, 0, 65, 25, "Settings");
      mnubtn_settings->menu(menu_mnubtn_settings);
    } // Fl_Menu_Button* mnubtn_settings
    { mnubtn_login = new Fl_Menu_Button(335, 0, 80, 25, "Log in/out");
      mnubtn_login->callback((Fl_Callback*)MENU_BTN_CB, (void*)(login_show));
    } // Fl_Menu_Button* mnubtn_login
    { mnubtn_register = new Fl_Menu_Button(415, 0, 75, 25, "Register");
      mnubtn_register->callback((Fl_Callback*)MENU_BTN_CB, (void*)(register_show));
    } // Fl_Menu_Button* mnubtn_register
    { // Clears workspace - shows backdrop
      menubtn_clear = new Fl_Menu_Button(485, 0, 55, 25, "Clear");
      menubtn_clear->callback((Fl_Callback*)MENU_BTN_CB, (void*)(clear_workspace));
    } // Fl_Menu_Button* menubtn_clear
    { // Register
      group_register = new Fl_Group(0, 25, 540, 335);
      group_register->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(195, 25, 155, 0, "Register");
        o->labelsize(41);
        o->align(Fl_Align(34));
      } // Fl_Text_Display* o
      { inp_usr-reg = new Fl_Input(105, 95, 435, 30, "Username");
        inp_usr-reg->labelsize(19);
      } // Fl_Input* inp_usr-reg
      { inp_pwd1-reg = new Fl_Input(105, 135, 435, 30, "Password");
        inp_pwd1-reg->labelsize(19);
      } // Fl_Input* inp_pwd1-reg
      { inp_pwd2-reg = new Fl_Input(120, 170, 420, 30, "Password again");
      } // Fl_Input* inp_pwd2-reg
      { cic_role-reg = new Fl_Input_Choice(325, 200, 195, 65, "Role");
        cic_role-reg->color((Fl_Color)34);
        cic_role-reg->selection_color((Fl_Color)34);
        cic_role-reg->labelsize(31);
        cic_role-reg->textsize(21);
      } // Fl_Input_Choice* cic_role-reg
      { btn_reg-reg = new Fl_Button(375, 290, 155, 70, "Register");
        btn_reg-reg->color((Fl_Color)25);
        btn_reg-reg->selection_color((Fl_Color)35);
        btn_reg-reg->labelsize(31);
        btn_reg-reg->callback((Fl_Callback*)BTN_CB, (void*)(REG));
      } // Fl_Button* btn_reg-reg
      { btn_clear-reg = new Fl_Button(190, 290, 180, 70, "Clear");
        btn_clear-reg->color((Fl_Color)25);
        btn_clear-reg->selection_color((Fl_Color)35);
        btn_clear-reg->labelsize(31);
        btn_clear-reg->callback((Fl_Callback*)BTN_CB, (void*)(CLS));
      } // Fl_Button* btn_clear-reg
      { btn_back-reg = new Fl_Button(5, 290, 180, 70, "Back");
        btn_back-reg->color((Fl_Color)25);
        btn_back-reg->selection_color((Fl_Color)27);
        btn_back-reg->labelsize(31);
        btn_back-reg->callback((Fl_Callback*)BTN_CB, (void*)(BACK));
      } // Fl_Button* btn_back-reg
      { chk_showpwd-reg = new Fl_Check_Button(15, 200, 35, 40, "Show password");
        chk_showpwd-reg->down_box(FL_DOWN_BOX);
        chk_showpwd-reg->labelsize(25);
        chk_showpwd-reg->callback((Fl_Callback*)BTN_CB, (void*)(showpwd_reg));
      } // Fl_Check_Button* chk_showpwd-reg
      { btn_help-reg = new Fl_Button(5, 30, 65, 30, "HELP");
        btn_help-reg->labelsize(25);
        btn_help-reg->callback((Fl_Callback*)BTN_CB, (void*)(HELP_REG));
      } // Fl_Button* btn_help-reg
      group_register->end();
      Fl_Group::current()->resizable(group_register);
    } // Fl_Group* group_register
    { // Login
      group_login = new Fl_Group(0, 25, 540, 340);
      group_login->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(200, 30, 155, 0, "Login");
        o->labelsize(41);
        o->align(Fl_Align(34));
      } // Fl_Text_Display* o
      { inp_usr-log = new Fl_Input(110, 90, 425, 30, "Username");
        inp_usr-log->labelsize(19);
      } // Fl_Input* inp_usr-log
      { inp_pwd-log = new Fl_Input(110, 125, 425, 30, "Password");
        inp_pwd-log->labelsize(19);
      } // Fl_Input* inp_pwd-log
      { chk_showpwd-log = new Fl_Check_Button(20, 175, 25, 25, "Show password");
        chk_showpwd-log->down_box(FL_DOWN_BOX);
        chk_showpwd-log->labelsize(31);
        chk_showpwd-log->callback((Fl_Callback*)BTN_CB, (void*)(showpwd_log));
      } // Fl_Check_Button* chk_showpwd-log
      { btn_login-log = new Fl_Button(365, 230, 175, 130, "LOGIN");
        btn_login-log->color((Fl_Color)25);
        btn_login-log->selection_color((Fl_Color)35);
        btn_login-log->labelsize(31);
        btn_login-log->callback((Fl_Callback*)BTN_CB, (void*)(LOGIN));
      } // Fl_Button* btn_login-log
      { btn_cls-log = new Fl_Button(180, 230, 180, 130, "Clear");
        btn_cls-log->color((Fl_Color)25);
        btn_cls-log->selection_color((Fl_Color)35);
        btn_cls-log->labelsize(31);
        btn_cls-log->callback((Fl_Callback*)BTN_CB, (void*)(CLS));
      } // Fl_Button* btn_cls-log
      { btn_back-log = new Fl_Button(10, 230, 160, 130, "Back");
        btn_back-log->color((Fl_Color)25);
        btn_back-log->selection_color((Fl_Color)35);
        btn_back-log->labelsize(31);
        btn_back-log->callback((Fl_Callback*)BTN_CB, (void*)(BACK));
      } // Fl_Button* btn_back-log
      { btn_help-log = new Fl_Button(5, 30, 75, 35, "HELP");
        btn_help-log->labelsize(21);
        btn_help-log->callback((Fl_Callback*)BTN_CB, (void*)(HELP_LOG));
      } // Fl_Button* btn_help-log
      group_login->end();
    } // Fl_Group* group_login
    { // Add Books
      group_addbooks = new Fl_Group(0, 25, 540, 335);
      group_addbooks->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(165, 25, 10, 30, "Add Books");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_title-addbk = new Fl_Input(50, 60, 410, 30, "Title");
        inp_title-addbk->labelsize(21);
      } // Fl_Input* inp_title-addbk
      { inp_id-addbk = new Fl_Input(85, 120, 160, 30, "Book ID");
        inp_id-addbk->labelsize(21);
      } // Fl_Input* inp_id-addbk
      { inp_author-addbk = new Fl_Input(75, 90, 385, 30, "Author");
        inp_author-addbk->labelsize(21);
      } // Fl_Input* inp_author-addbk
      { // Checks if title already exists
        btn_checkitle-addbk = new Fl_Button(460, 60, 80, 30, "Check Title");
        btn_checkitle-addbk->callback((Fl_Callback*)BTN_CB, (void*)(checktitle_addbk));
      } // Fl_Button* btn_checkitle-addbk
      { // Check if author already exists
        btn_checkauthor-addbk = new Fl_Button(460, 90, 80, 30, "Check Author");
        btn_checkauthor-addbk->labelsize(12);
        btn_checkauthor-addbk->callback((Fl_Callback*)BTN_CB, (void*)(checkauthor_addbk));
      } // Fl_Button* btn_checkauthor-addbk
      { // Checks f ID already exists
        btn_checkid-addbk = new Fl_Button(460, 120, 80, 30, "Check ID");
        btn_checkid-addbk->callback((Fl_Callback*)BTN_CB, (void*)(checkid-addbk));
      } // Fl_Button* btn_checkid-addbk
      { chk_nonnumeric-addbk = new Fl_Check_Button(370, 120, 90, 30, "Non-numeric");
        chk_nonnumeric-addbk->down_box(FL_DOWN_BOX);
        chk_nonnumeric-addbk->labelsize(12);
        chk_nonnumeric-addbk->callback((Fl_Callback*)BTN_CB, (void*)(nonnumeric_addbk));
      } // Fl_Check_Button* chk_nonnumeric-addbk
      { chk_automaticallycheckid-addbk = new Fl_Check_Button(240, 120, 125, 30, "Automatically check ID");
        chk_automaticallycheckid-addbk->down_box(FL_DOWN_BOX);
        chk_automaticallycheckid-addbk->labelsize(12);
        chk_automaticallycheckid-addbk->callback((Fl_Callback*)BTN_CB, (void*)(automaticallycheckid-addbk));
      } // Fl_Check_Button* chk_automaticallycheckid-addbk
      { cic_category-addbk = new Fl_Choice(65, 150, 200, 25, "Category");
        cic_category-addbk->down_box(FL_BORDER_BOX);
        cic_category-addbk->callback((Fl_Callback*)BTN_CB, (void*)(category_addbk));
      } // Fl_Choice* cic_category-addbk
      { cic_status-addbk = new Fl_Choice(315, 150, 225, 25, "Status");
        cic_status-addbk->down_box(FL_BORDER_BOX);
        cic_status-addbk->callback((Fl_Callback*)BTN_CB, (void*)(status_addbk));
      } // Fl_Choice* cic_status-addbk
      { btn_addbook-addbk = new Fl_Button(225, 175, 315, 40, "ADD BOOK");
        btn_addbook-addbk->labelsize(21);
        btn_addbook-addbk->callback((Fl_Callback*)BTN_CB, (void*)(ADDBOOK));
      } // Fl_Button* btn_addbook-addbk
      { btn_undoadd-addbk = new Fl_Button(5, 175, 210, 40, "Undo last add");
        btn_undoadd-addbk->labelsize(21);
        btn_undoadd-addbk->callback((Fl_Callback*)BTN_CB, (void*)(undoadd_addbk));
      } // Fl_Button* btn_undoadd-addbk
      { Fl_Text_Display* o = new Fl_Text_Display(205, 215, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_search-addbk = new Fl_Input(95, 245, 235, 30, "Search term:");
        inp_search-addbk->labelsize(16);
      } // Fl_Input* inp_search-addbk
      { cic_searchby-addbk = new Fl_Choice(330, 245, 105, 25, "Search by:");
        cic_searchby-addbk->down_box(FL_BORDER_BOX);
        cic_searchby-addbk->labelsize(17);
        cic_searchby-addbk->callback((Fl_Callback*)BTN_CB, (void*)(searchby_addbk));
        cic_searchby-addbk->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby-addbk
      { btn_search-addbk = new Fl_Button(435, 225, 105, 45, "SEARCH");
        btn_search-addbk->labelsize(21);
        btn_search-addbk->callback((Fl_Callback*)BTN_CB, (void*)(search_addbk));
      } // Fl_Button* btn_search-addbk
      { // Search results, click to fill text fields
        brw_search-addbk = new Fl_Browser(5, 270, 535, 90);
        brw_search-addbk->callback((Fl_Callback*)BTN_CB, (void*)(browser_addbk));
      } // Fl_Browser* brw_search-addbk
      { btn_help-addbk = new Fl_Button(0, 30, 70, 30, "HELP");
        btn_help-addbk->labelsize(21);
        btn_help-addbk->callback((Fl_Callback*)BTN_CB, (void*)(HELP_ADDBK));
      } // Fl_Button* btn_help-addbk
      group_addbooks->end();
    } // Fl_Group* group_addbooks
    { // Add Readers
      group_addreaders = new Fl_Group(-10, 25, 555, 345);
      group_addreaders->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(150, 25, 10, 30, "Add Readers");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_name-addrdr = new Fl_Input(60, 60, 380, 30, "Name");
        inp_name-addrdr->labelsize(21);
      } // Fl_Input* inp_name-addrdr
      { btn_name-addrdr = new Fl_Button(440, 60, 100, 30, "Check Name");
        btn_name-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(checkname_addrdr));
      } // Fl_Button* btn_name-addrdr
      { inp_surname-addrdr = new Fl_Input(70, 90, 370, 30, "Surname");
        inp_surname-addrdr->labelsize(16);
      } // Fl_Input* inp_surname-addrdr
      { inp_grade-addrdr = new Fl_Input(45, 120, 20, 30, "Grade");
        inp_grade-addrdr->labelsize(15);
      } // Fl_Input* inp_grade-addrdr
      { btn_checksurname-addrdr = new Fl_Button(440, 90, 100, 30, "Check Surname");
        btn_checksurname-addrdr->labelsize(12);
        btn_checksurname-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(checksurname_addrdr));
      } // Fl_Button* btn_checksurname-addrdr
      { inp_class-addrdr = new Fl_Input(110, 120, 20, 30, "Class");
        inp_class-addrdr->labelsize(15);
      } // Fl_Input* inp_class-addrdr
      { inp_readerid-addrdr = new Fl_Input(200, 120, 105, 30, "Reader ID");
        inp_readerid-addrdr->labelsize(15);
      } // Fl_Input* inp_readerid-addrdr
      { chk_nonnumeric-addrdr = new Fl_Check_Button(305, 140, 90, 30, "Non-numeric");
        chk_nonnumeric-addrdr->down_box(FL_DOWN_BOX);
        chk_nonnumeric-addrdr->labelsize(12);
        chk_nonnumeric-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(nonnumeric_addrdr));
      } // Fl_Check_Button* chk_nonnumeric-addrdr
      { chk_automaticallycheckid-addrdr = new Fl_Check_Button(305, 120, 170, 30, "Automatically check ID");
        chk_automaticallycheckid-addrdr->down_box(FL_DOWN_BOX);
        chk_automaticallycheckid-addrdr->labelsize(13);
        chk_automaticallycheckid-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(automaticallycheckid_addrdr));
      } // Fl_Check_Button* chk_automaticallycheckid-addrdr
      { checkid-addrdr = new Fl_Button(460, 120, 80, 30, "Check ID");
        checkid-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(checkid_addrdr));
      } // Fl_Button* checkid-addrdr
      { btn_addreader-addrdr = new Fl_Button(250, 165, 290, 40, "ADD READER");
        btn_addreader-addrdr->labelsize(31);
        btn_addreader-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(addreader_addrdr));
      } // Fl_Button* btn_addreader-addrdr
      { btn_undolastadd-addrdr = new Fl_Button(0, 165, 245, 40, "Undo last add");
        btn_undolastadd-addrdr->labelsize(25);
        btn_undolastadd-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(undolastadd_addrdr));
      } // Fl_Button* btn_undolastadd-addrdr
      { Fl_Text_Display* o = new Fl_Text_Display(210, 205, 10, 30, "Search");
        o->labelsize(32);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { cic_searchby-addrdr = new Fl_Choice(330, 255, 105, 25, "Search by:");
        cic_searchby-addrdr->down_box(FL_BORDER_BOX);
        cic_searchby-addrdr->labelsize(17);
        cic_searchby-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(searchby_addrdr));
        cic_searchby-addrdr->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby-addrdr
      { btn_search-addrdr = new Fl_Button(435, 235, 105, 45, "SEARCH");
        btn_search-addrdr->labelsize(21);
        btn_search-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(search_addrdr));
      } // Fl_Button* btn_search-addrdr
      { // Search results, click to fill text fields
        brw_search-addrdr = new Fl_Browser(5, 280, 535, 90);
        brw_search-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(browser_addrdr));
      } // Fl_Browser* brw_search-addrdr
      { inp_search-addrdr = new Fl_Input(90, 240, 240, 40, "Search term:");
      } // Fl_Input* inp_search-addrdr
      { btn_help-addrdr = new Fl_Button(5, 25, 75, 35, "HELP");
        btn_help-addrdr->labelsize(21);
        btn_help-addrdr->callback((Fl_Callback*)BTN_CB, (void*)(HELP_addrdr));
      } // Fl_Button* btn_help-addrdr
      group_addreaders->end();
    } // Fl_Group* group_addreaders
    { // Add loans
      group_addloans = new Fl_Group(0, 25, 540, 350);
      group_addloans->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(170, 25, 10, 30, "Add Loans");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_bookid-addlns = new Fl_Input(55, 60, 65, 30, "Book ID");
      } // Fl_Input* inp_bookid-addlns
      { cic_searchby-addlns = new Fl_Choice(430, 175, 105, 25, "Search by:");
        cic_searchby-addlns->down_box(FL_BORDER_BOX);
        cic_searchby-addlns->labelsize(17);
        cic_searchby-addlns->callback((Fl_Callback*)BTN_CB, (void*)(searchby_addlns));
        cic_searchby-addlns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby-addlns
      { btn_search-addlns = new Fl_Button(10, 200, 525, 30, "SEARCH");
        btn_search-addlns->labelsize(21);
        btn_search-addlns->callback((Fl_Callback*)BTN_CB, (void*)(search_addlns));
      } // Fl_Button* btn_search-addlns
      { // Search results, click to fill text fields
        brw_search-addlns = new Fl_Browser(5, 230, 535, 140);
        brw_search-addlns->callback((Fl_Callback*)BTN_CB, (void*)(browser_addlns));
      } // Fl_Browser* brw_search-addlns
      { inp_search-addlns = new Fl_Input(85, 160, 235, 40, "Search term:");
      } // Fl_Input* inp_search-addlns
      { cic_searchwhat-addlns = new Fl_Choice(320, 175, 105, 25, "Search what:");
        cic_searchwhat-addlns->down_box(FL_BORDER_BOX);
        cic_searchwhat-addlns->labelsize(17);
        cic_searchwhat-addlns->callback((Fl_Callback*)BTN_CB, (void*)(searchwhat_addlns));
        cic_searchwhat-addlns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchwhat-addlns
      { inp_readerid-addlns = new Fl_Input(190, 60, 65, 30, "Reader ID");
      } // Fl_Input* inp_readerid-addlns
      { inp_loanid-addlns = new Fl_Input(310, 60, 65, 30, "Loan ID");
      } // Fl_Input* inp_loanid-addlns
      { inp_expirydate-addlns = new Fl_Input(175, 90, 85, 30, "Expiry date (yyyy-mm-dd): ");
      } // Fl_Input* inp_expirydate-addlns
      { chk_generate-addlns = new Fl_Check_Button(375, 60, 25, 25, "Generate ID");
        chk_generate-addlns->down_box(FL_DOWN_BOX);
        chk_generate-addlns->labelsize(17);
        chk_generate-addlns->callback((Fl_Callback*)BTN_CB, (void*)(generate_addlns));
      } // Fl_Check_Button* chk_generate-addlns
      { Fl_Text_Display* o = new Fl_Text_Display(355, 90, 185, 25, "Current date:");
        o->align(Fl_Align(FL_ALIGN_LEFT));
      } // Fl_Text_Display* o
      { btn_addloan-addlns = new Fl_Button(225, 120, 310, 30, "ADD LOAN");
        btn_addloan-addlns->labelsize(21);
        btn_addloan-addlns->callback((Fl_Callback*)BTN_CB, (void*)(ADDLOAN));
      } // Fl_Button* btn_addloan-addlns
      { btn_undolastadd-addlns = new Fl_Button(0, 120, 220, 30, "Undo last loan");
        btn_undolastadd-addlns->labelsize(21);
        btn_undolastadd-addlns->callback((Fl_Callback*)BTN_CB, (void*)(undolastadd_addlns));
      } // Fl_Button* btn_undolastadd-addlns
      { btn_help-addlns = new Fl_Button(5, 25, 75, 35, "HELP");
        btn_help-addlns->labelsize(21);
        btn_help-addlns->callback((Fl_Callback*)BTN_CB, (void*)(HELP_addlns));
      } // Fl_Button* btn_help-addlns
      group_addloans->end();
    } // Fl_Group* group_addloans
    { // edit books
      group_editbooks = new Fl_Group(0, 25, 540, 335);
      group_editbooks->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(205, 210, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_searchterm-editbk = new Fl_Input(95, 240, 235, 30, "Search term:");
        inp_searchterm-editbk->labelsize(16);
      } // Fl_Input* inp_searchterm-editbk
      { cic_searchby-editbk = new Fl_Choice(330, 240, 105, 25, "Search by:");
        cic_searchby-editbk->down_box(FL_BORDER_BOX);
        cic_searchby-editbk->labelsize(17);
        cic_searchby-editbk->callback((Fl_Callback*)BTN_CB, (void*)(searchby_editbk));
        cic_searchby-editbk->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby-editbk
      { btn_search-editbk = new Fl_Button(435, 220, 105, 45, "SEARCH");
        btn_search-editbk->labelsize(21);
        btn_search-editbk->callback((Fl_Callback*)BTN_CB, (void*)(search_editbk));
      } // Fl_Button* btn_search-editbk
      { // Search results, click to fill text fields
        brw_search-editbk = new Fl_Browser(5, 265, 535, 90);
        brw_search-editbk->callback((Fl_Callback*)BTN_CB, (void*)(browser_editbk));
      } // Fl_Browser* brw_search-editbk
      { btn_help-editbk = new Fl_Button(0, 25, 70, 30, "HELP");
        btn_help-editbk->labelsize(21);
        btn_help-editbk->callback((Fl_Callback*)BTN_CB, (void*)(HELP_editbk));
      } // Fl_Button* btn_help-editbk
      { Fl_Text_Display* o = new Fl_Text_Display(165, 25, 10, 30, "Edit Books");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_title-editbk = new Fl_Input(45, 60, 410, 30, "Title");
        inp_title-editbk->labelsize(21);
      } // Fl_Input* inp_title-editbk
      { btn_checktitle-editbk = new Fl_Button(460, 60, 80, 30, "Check Title");
        btn_checktitle-editbk->callback((Fl_Callback*)BTN_CB, (void*)(checktitle_editbk));
      } // Fl_Button* btn_checktitle-editbk
      { inp_author-editbk = new Fl_Input(65, 90, 390, 30, "Author");
        inp_author-editbk->labelsize(21);
      } // Fl_Input* inp_author-editbk
      { inp_bookid-editbk = new Fl_Input(80, 120, 160, 30, "Book ID");
        inp_bookid-editbk->labelsize(21);
      } // Fl_Input* inp_bookid-editbk
      { btn_checkauthor-editbk = new Fl_Button(460, 90, 80, 30, "Check Author");
        btn_checkauthor-editbk->labelsize(12);
        btn_checkauthor-editbk->callback((Fl_Callback*)BTN_CB, (void*)(checkauthor_editbk));
      } // Fl_Button* btn_checkauthor-editbk
      { btn_checktitle-editbk = new Fl_Button(460, 120, 80, 30, "Check Title");
        btn_checktitle-editbk->callback((Fl_Callback*)BTN_CB, (void*)(checktitle_editbk));
      } // Fl_Button* btn_checktitle-editbk
      { chk_nonnumeric-editbk = new Fl_Check_Button(365, 120, 90, 30, "Non-numeric");
        chk_nonnumeric-editbk->down_box(FL_DOWN_BOX);
        chk_nonnumeric-editbk->labelsize(12);
        chk_nonnumeric-editbk->callback((Fl_Callback*)BTN_CB, (void*)(nonnumeric_editbk));
      } // Fl_Check_Button* chk_nonnumeric-editbk
      { chk_automaticallycheck-editbk = new Fl_Check_Button(240, 120, 125, 30, "Automatically check");
        chk_automaticallycheck-editbk->down_box(FL_DOWN_BOX);
        chk_automaticallycheck-editbk->labelsize(12);
        chk_automaticallycheck-editbk->callback((Fl_Callback*)BTN_CB, (void*)(automaticallycheck_editbk));
      } // Fl_Check_Button* chk_automaticallycheck-editbk
      { cic_category-editbk = new Fl_Choice(65, 150, 200, 25, "Category");
        cic_category-editbk->down_box(FL_BORDER_BOX);
        cic_category-editbk->callback((Fl_Callback*)BTN_CB, (void*)(category_editbk));
      } // Fl_Choice* cic_category-editbk
      { cic_status-editbk = new Fl_Choice(315, 150, 225, 25, "Status");
        cic_status-editbk->down_box(FL_BORDER_BOX);
        cic_status-editbk->callback((Fl_Callback*)BTN_CB, (void*)(status_editbk));
      } // Fl_Choice* cic_status-editbk
      { btn_editbook-editbk = new Fl_Button(225, 175, 315, 40, "EDIT BOOK");
        btn_editbook-editbk->labelsize(21);
        btn_editbook-editbk->callback((Fl_Callback*)BTN_CB, (void*)(EDITBOOK));
      } // Fl_Button* btn_editbook-editbk
      { btn_undolastedit-editbk = new Fl_Button(5, 175, 210, 40, "Undo last edit");
        btn_undolastedit-editbk->labelsize(21);
        btn_undolastedit-editbk->callback((Fl_Callback*)BTN_CB, (void*)(undolastedit_editbk));
      } // Fl_Button* btn_undolastedit-editbk
      group_editbooks->end();
    } // Fl_Group* group_editbooks
    { // delete books
      group_deletebooks = new Fl_Group(0, 25, 540, 335);
      { Fl_Text_Display* o = new Fl_Text_Display(205, 60, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_search-delbks = new Fl_Input(95, 90, 235, 30, "Search term:");
        inp_search-delbks->labelsize(16);
      } // Fl_Input* inp_search-delbks
      { cic_searchby-delbks = new Fl_Choice(330, 95, 105, 25, "Search by:");
        cic_searchby-delbks->down_box(FL_BORDER_BOX);
        cic_searchby-delbks->labelsize(17);
        cic_searchby-delbks->callback((Fl_Callback*)BTN_CB, (void*)(searchby_delbks));
        cic_searchby-delbks->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby-delbks
      { btn_search-delbks = new Fl_Button(435, 75, 105, 45, "SEARCH");
        btn_search-delbks->labelsize(21);
        btn_search-delbks->callback((Fl_Callback*)BTN_CB, (void*)(search_delbks));
      } // Fl_Button* btn_search-delbks
      { // Search results, click to fill text fields
        brw_search-delbks = new Fl_Browser(5, 125, 535, 90);
        brw_search-delbks->callback((Fl_Callback*)BTN_CB, (void*)(browser_delbks));
      } // Fl_Browser* brw_search-delbks
      { btn_help-delbks = new Fl_Button(0, 25, 70, 30, "HELP");
        btn_help-delbks->labelsize(21);
        btn_help-delbks->callback((Fl_Callback*)BTN_CB, (void*)(HELP_delbks));
      } // Fl_Button* btn_help-delbks
      { Fl_Text_Display* o = new Fl_Text_Display(155, 25, 10, 30, "Delete Books");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_bookid-delbks = new Fl_Input(475, 250, 65, 25, "Book ID:");
        inp_bookid-delbks->labelsize(16);
        inp_bookid-delbks->callback((Fl_Callback*)BTN_CB, (void*)(bookid_delbks));
      } // Fl_Input* inp_bookid-delbks
      { btn_deletebook-delbks = new Fl_Button(330, 215, 210, 35, "DELETE BOOK");
        btn_deletebook-delbks->labelsize(21);
        btn_deletebook-delbks->callback((Fl_Callback*)BTN_CB, (void*)(DELTEBOOK));
      } // Fl_Button* btn_deletebook-delbks
      { btn_undolastdelete-delbks = new Fl_Button(190, 215, 140, 35, "Undo last delete");
        btn_undolastdelete-delbks->labelsize(16);
        btn_undolastdelete-delbks->callback((Fl_Callback*)BTN_CB, (void*)(undolastdelete_delbks));
      } // Fl_Button* btn_undolastdelete-delbks
      { Fl_Text_Display* o = new Fl_Text_Display(135, 250, 10, 30, "Search deleted books");
        o->labelsize(17);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { // Search results, click to fill text fields
        brw_searchdeleted-delbks = new Fl_Browser(5, 275, 535, 85);
        brw_searchdeleted-delbks->callback((Fl_Callback*)BTN_CB, (void*)(browserdeleted_delbks));
      } // Fl_Browser* brw_searchdeleted-delbks
      { btn_restoreselected-delbks = new Fl_Button(5, 250, 130, 25, "Restore selected");
        btn_restoreselected-delbks->labelsize(16);
        btn_restoreselected-delbks->callback((Fl_Callback*)BTN_CB, (void*)(restoreselected_delbks));
      } // Fl_Button* btn_restoreselected-delbks
      { btn_searchdeleted-delbks = new Fl_Button(325, 250, 80, 25, "Search");
        btn_searchdeleted-delbks->labelsize(17);
        btn_searchdeleted-delbks->callback((Fl_Callback*)BTN_CB, (void*)(searchdeleted_delbks));
      } // Fl_Button* btn_searchdeleted-delbks
      group_deletebooks->end();
    } // Fl_Group* group_deletebooks
    { // Edit readers
      group_editreaders = new Fl_Group(0, 25, 540, 345);
      group_editreaders->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(150, 25, 10, 30, "Edit Readers");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { Fl_Input* o = new Fl_Input(60, 60, 380, 30, "Name");
        o->labelsize(21);
      } // Fl_Input* o
      { new Fl_Button(440, 60, 100, 30, "Check Name");
      } // Fl_Button* o
      { Fl_Input* o = new Fl_Input(70, 90, 370, 30, "Surname");
        o->labelsize(16);
      } // Fl_Input* o
      { Fl_Input* o = new Fl_Input(45, 120, 20, 30, "Grade");
        o->labelsize(15);
      } // Fl_Input* o
      { Fl_Button* o = new Fl_Button(440, 90, 100, 30, "Check Surname");
        o->labelsize(12);
      } // Fl_Button* o
      { Fl_Input* o = new Fl_Input(110, 120, 20, 30, "Class");
        o->labelsize(15);
      } // Fl_Input* o
      { Fl_Input* o = new Fl_Input(200, 120, 105, 30, "Reader ID");
        o->labelsize(15);
      } // Fl_Input* o
      { Fl_Check_Button* o = new Fl_Check_Button(305, 140, 90, 30, "Non-numeric");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(12);
      } // Fl_Check_Button* o
      { Fl_Check_Button* o = new Fl_Check_Button(305, 120, 170, 30, "Automatically check ID");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(13);
      } // Fl_Check_Button* o
      { new Fl_Button(460, 120, 80, 30, "Check ID");
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(250, 165, 290, 40, "EDIT READER");
        o->labelsize(31);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(0, 165, 245, 40, "Undo last add");
        o->labelsize(25);
      } // Fl_Button* o
      { Fl_Text_Display* o = new Fl_Text_Display(210, 205, 10, 30, "Search");
        o->labelsize(32);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { Fl_Choice* o = new Fl_Choice(330, 255, 105, 25, "Search by:");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(17);
        o->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* o
      { Fl_Button* o = new Fl_Button(435, 235, 105, 45, "SEARCH");
        o->labelsize(21);
      } // Fl_Button* o
      { // Search results, click to fill text fields
        new Fl_Browser(5, 280, 535, 90);
      } // Fl_Browser* o
      { new Fl_Input(90, 240, 240, 40, "Search term:");
      } // Fl_Input* o
      { Fl_Button* o = new Fl_Button(5, 25, 75, 35, "HELP");
        o->labelsize(21);
      } // Fl_Button* o
      group_editreaders->end();
    } // Fl_Group* group_editreaders
    { // Delete readers
      group_deletereaders = new Fl_Group(0, 25, 540, 340);
      group_deletereaders->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(205, 60, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { Fl_Input* o = new Fl_Input(95, 90, 235, 30, "Search term:");
        o->labelsize(16);
      } // Fl_Input* o
      { Fl_Choice* o = new Fl_Choice(330, 95, 105, 25, "Search by:");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(17);
        o->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* o
      { Fl_Button* o = new Fl_Button(435, 75, 105, 45, "SEARCH");
        o->labelsize(21);
      } // Fl_Button* o
      { // Search results, click to fill text fields
        new Fl_Browser(5, 125, 535, 90);
      } // Fl_Browser* o
      { Fl_Button* o = new Fl_Button(0, 25, 70, 30, "HELP");
        o->labelsize(21);
      } // Fl_Button* o
      { Fl_Text_Display* o = new Fl_Text_Display(130, 25, 10, 30, "Delete Readers");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { Fl_Input* o = new Fl_Input(70, 215, 120, 35, "Book ID:");
        o->labelsize(16);
      } // Fl_Input* o
      { Fl_Button* o = new Fl_Button(330, 215, 210, 35, "DELETE READER");
        o->labelsize(21);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(190, 215, 140, 35, "Undo last delete");
        o->labelsize(16);
      } // Fl_Button* o
      { Fl_Text_Display* o = new Fl_Text_Display(175, 250, 10, 30, "Search deleted readers");
        o->labelsize(21);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { // Search results, click to fill text fields
        new Fl_Browser(5, 275, 535, 85);
      } // Fl_Browser* o
      { Fl_Button* o = new Fl_Button(5, 250, 170, 25, "Restore selected");
        o->labelsize(16);
      } // Fl_Button* o
      group_deletereaders->end();
    } // Fl_Group* group_deletereaders
    { // Edit loans
      group_editloans = new Fl_Group(0, 25, 540, 355);
      group_editloans->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(170, 25, 10, 30, "Edit Loans");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { new Fl_Input(55, 60, 65, 30, "Book ID");
      } // Fl_Input* o
      { Fl_Choice* o = new Fl_Choice(430, 175, 105, 25, "Search by:");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(17);
        o->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* o
      { Fl_Button* o = new Fl_Button(10, 200, 525, 30, "SEARCH");
        o->labelsize(21);
      } // Fl_Button* o
      { // Search results, click to fill text fields
        new Fl_Browser(5, 230, 535, 140);
      } // Fl_Browser* o
      { new Fl_Input(85, 160, 235, 40, "Search term:");
      } // Fl_Input* o
      { Fl_Choice* o = new Fl_Choice(320, 175, 105, 25, "Search:");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(17);
        o->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* o
      { new Fl_Input(190, 60, 65, 30, "Reader ID");
      } // Fl_Input* o
      { new Fl_Input(310, 60, 65, 30, "Loan ID");
      } // Fl_Input* o
      { Fl_Check_Button* o = new Fl_Check_Button(375, 60, 110, 30, "auto-generate");
        o->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* o
      { new Fl_Input(175, 90, 85, 30, "Expiry date (yyyy-mm-dd): ");
      } // Fl_Input* o
      { Fl_Text_Display* o = new Fl_Text_Display(345, 90, 185, 25, "Current date:");
        o->align(Fl_Align(FL_ALIGN_LEFT));
      } // Fl_Text_Display* o
      { Fl_Button* o = new Fl_Button(225, 120, 310, 30, "EDIT LOAN");
        o->labelsize(21);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(0, 120, 220, 30, "Undo last loan edit");
        o->labelsize(21);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(5, 25, 75, 35, "HELP");
        o->labelsize(21);
      } // Fl_Button* o
      group_editloans->end();
    } // Fl_Group* group_editloans
    { // mark loans 
      group_markloans = new Fl_Group(0, 25, 545, 350);
      group_markloans->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(170, 25, 10, 30, "Mark Loans");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { Fl_Choice* o = new Fl_Choice(430, 75, 105, 25, "Search by:");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(17);
        o->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* o
      { Fl_Button* o = new Fl_Button(10, 100, 525, 30, "SEARCH");
        o->labelsize(21);
      } // Fl_Button* o
      { // Search results, click to fill text fields
        new Fl_Browser(5, 130, 535, 140);
      } // Fl_Browser* o
      { new Fl_Input(90, 60, 235, 40, "Search term:");
      } // Fl_Input* o
      { Fl_Choice* o = new Fl_Choice(325, 75, 105, 25, "Search:");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(17);
        o->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* o
      { Fl_Button* o = new Fl_Button(5, 25, 75, 35, "HELP");
        o->labelsize(21);
      } // Fl_Button* o
      { Fl_Input* o = new Fl_Input(140, 275, 100, 30, "Prolong by (days)");
        o->labelsize(17);
      } // Fl_Input* o
      { Fl_Button* o = new Fl_Button(240, 275, 140, 30, "Prolong");
        o->labelsize(18);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(385, 275, 150, 30, "Mark as returned");
        o->labelsize(18);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(385, 310, 150, 30, "Mark as lost");
        o->labelsize(18);
      } // Fl_Button* o
      group_markloans->end();
    } // Fl_Group* group_markloans
    o->end();
  } // Fl_Double_Window* o
  return window_assistant;
}

/**
 For non-menu buttons (the ones in groups)
*/
void BTN_CB(Fl_Widget* w, void* data) {
  // Cast the user data to the appropriate type (in this case, int)
      std::string function_data = *(std::string*)data;
  
      // debug
      std::cout << "BTN_CB called with " << function_data << " as data. \n";
      if (function_data == "login_btn")
      {
          std::cout << "Login button clicked! \n";
          //std::string usr = username_input->value(); // -> here, username_inp>
          //std::string pwd = password_input->value();
  
  
      }
      else { //incorrect function id
              std::cerr << "Unknown function data: " << function_data << " - this is a programmer error \n";
      }
}

/**
 Hides all groups
*/
void hide_all_groups() {
  group_register.hide();
  group_login().hide;
  group_addbooks().hide;
  group_addreaders().hide;
  group_addloans().hide;
}
