// generated by Fast Light User Interface Designer (fluid) version 1.0311

#ifndef shelfsight_gui_h
#define shelfsight_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window_assistant;
#include <FL/Fl_Text_Display.H>
extern Fl_Image *assistant_image;
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Button.H>
extern Fl_Menu_Button *mnubtn_books;
extern Fl_Menu_Button *mnubtn_readers;
extern Fl_Menu_Button *mnubtn_loans;
extern Fl_Menu_Button *mnubtn_databases;
extern Fl_Menu_Button *mnubtn_settings;
extern Fl_Menu_Button *mnubtn_login;
extern Fl_Menu_Button *mnubtn_register;
extern Fl_Menu_Button *menubtn_clear;
#include <FL/Fl_Group.H>
extern Fl_Group *group_register;
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Check_Button.H>
extern Fl_Group *group_login;
extern Fl_Group *group_addbooks;
#include <FL/Fl_Choice.H>
#include <FL/Fl_Browser.H>
extern Fl_Group *group_addreaders;
extern Fl_Group *group_addloans;
extern Fl_Group *group_editbooks;
extern Fl_Group *group_deletebooks;
extern Fl_Group *group_editreaders;
extern Fl_Group *group_deletereaders;
extern Fl_Group *group_editloans;
extern Fl_Group *group_markloans;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_mnubtn_books[];
#define mnu_addbooks (menu_mnubtn_books+0)
#define mnu_editbooks (menu_mnubtn_books+1)
#define mnu_removebooks (menu_mnubtn_books+2)
#define mnu_managecategories (menu_mnubtn_books+3)
extern Fl_Menu_Item menu_mnubtn_readers[];
#define mnu_addreaders (menu_mnubtn_readers+0)
#define mnu_editreaders (menu_mnubtn_readers+1)
#define mnu_removereaders (menu_mnubtn_readers+2)
#define mnu_importreaders (menu_mnubtn_readers+3)
extern Fl_Menu_Item menu_mnubtn_loans[];
#define mnu_addloans (menu_mnubtn_loans+0)
#define mnu_editloans (menu_mnubtn_loans+1)
#define mnu_removeloans (menu_mnubtn_loans+2)
#define mnu_expiredloans (menu_mnubtn_loans+3)
extern Fl_Menu_Item menu_mnubtn_databases[];
#define mnu_loaddefaultdbs (menu_mnubtn_databases+0)
#define sbmnu_backup (menu_mnubtn_databases+1)
#define mnu_offlinebackup (menu_mnubtn_databases+2)
#define sbmnu_online (menu_mnubtn_databases+3)
#define mnu_directconnection (menu_mnubtn_databases+4)
#define mnu_localp2p (menu_mnubtn_databases+5)
#define mnu_onlinep2p (menu_mnubtn_databases+6)
#define sbmnu_managedbs (menu_mnubtn_databases+9)
#define mnu_adddb (menu_mnubtn_databases+10)
#define mnu_editdb (menu_mnubtn_databases+11)
#define mnu_selectcurrentdbs (menu_mnubtn_databases+12)
#define mnu_selectdefaultdbs (menu_mnubtn_databases+13)
extern Fl_Menu_Item menu_mnubtn_settings[];
#define mnu_account (menu_mnubtn_settings+0)
#define mnu_theme (menu_mnubtn_settings+1)
#define mnu_performance (menu_mnubtn_settings+2)
#define mnu_networking (menu_mnubtn_settings+3)
#define mnu_other (menu_mnubtn_settings+4)
void MENU_BTN_CB(Fl_Widget* w, void* data);
void BTN_CB(Fl_Widget* w, void* data);
void hide_all_groups();
#endif
